import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import puppeteer from 'puppeteer';
import JSZip from 'jszip';
import { Buffer } from 'node:buffer';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';
import { exportHtmlToPptx } from '../node-exporter.js';
import {
  EMU_PER_PT,
  PX_TO_PT,
  X_TOLERANCE_PT,
  Y_TOLERANCE_PT,
  analyzePage,
  measureBrowserPages,
  parseOfficeWords,
} from './helpers/office-fidelity.js';

// The fidelity matrix of OrgLith's closed slide subset (org-graph ADR
// 2026-09-24): one probe per allowed construct, generated by org-graph
// (frontend/src/export-render/presentationSubsetProbes.ts) and run through its
// production adapter. A construct belongs in the subset only if its probe is
// clean here. Every probe is compared three ways:
//   text     — where Office puts its words against the browser (helpers/office-fidelity.js)
//   paint    — the probe's box in the Office rendering against the browser screenshot
//   pictures — a probe without an image of its own must stay native, not become a picture

const runOfficeRoundtrip = process.env.DOM_TO_PPTX_OFFICE_ROUNDTRIP === '1';
const officeDescribe = runOfficeRoundtrip ? describe : describe.skip;

const FIXTURE = path.resolve('src/__tests__/fixtures/subset-matrix-deck.html');
const CANVAS = { width: 1280, height: 720 };
const PROBE_IDS = [
  ...new Set(Array.from(readFileSync(FIXTURE, 'utf8').matchAll(/data-probe="([^"]+)"/g), (match) => match[1])),
];

// Paint comparison works on 8 px blocks, so anti-aliasing does not count; a block
// differs when one channel of its average colour is further apart than
// BLOCK_COLOUR_LIMIT from every Office block within the text tolerances
// (X_TOLERANCE_PT, Y_TOLERANCE_PT). Where things sit is the text check's call;
// this one asks whether the paint is there — a lost fill or colour matches at no
// offset, a shifted line of text matches at one.
const BLOCK_PX = 8;
const BLOCK_COLOUR_LIMIT = 48;
const PAINT_DIFFERING_BLOCKS_LIMIT = 0.08;
const SHIFT_X_PX = Math.floor(X_TOLERANCE_PT / PX_TO_PT);
const SHIFT_Y_PX = Math.floor(Y_TOLERANCE_PT / PX_TO_PT);
// A picture counts as covering a probe when it lies over this share of its box.
const PICTURE_COVER_LIMIT = 0.5;

// Defect kinds per probe today. A clean probe is absent; an entry means the
// construct is not faithful yet and must be fixed here or leave the subset.
// Keep the kinds, not the measured numbers: those vary with fonts and builds.
const KNOWN_DEFECTS = {};

let outputDir;
let browserPages;
let slideIds;
let findingsByProbe;
let metricsByProbe;
let slideXmlAll;

async function screenshotSlides(executablePath) {
  const browser = await puppeteer.launch({ executablePath, headless: true, args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    await page.setViewport(CANVAS);
    await page.goto(pathToFileURL(FIXTURE).href, { waitUntil: 'load' });
    await page.evaluate(() => document.fonts.ready);
    const withImages = await page.evaluate(() =>
      Array.from(document.querySelectorAll('[data-probe]'))
        .filter((element) => element.querySelector('img, svg'))
        .map((element) => element.dataset.probe)
    );
    const shots = [];
    for (const slide of await page.$$('.slide')) shots.push(await slide.screenshot({ encoding: 'base64' }));
    return { shots, withImages: new Set(withImages) };
  } finally {
    await browser.close();
  }
}

/** Share of 8 px blocks inside each box whose paint Office does not have within the text tolerances. */
async function comparePaint(executablePath, browserShots, officeShots, boxesPerSlide) {
  const browser = await puppeteer.launch({ executablePath, headless: true, args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    const results = [];
    for (let index = 0; index < browserShots.length; index++) {
      results.push(
        ...(await page.evaluate(
          async ({ left, right, boxes, block, limit, canvas, shiftX, shiftY }) => {
            const pixels = async (data) => {
              const image = new Image();
              image.src = `data:image/png;base64,${data}`;
              await image.decode();
              const element = document.createElement('canvas');
              element.width = canvas.width;
              element.height = canvas.height;
              const context = element.getContext('2d');
              context.drawImage(image, 0, 0, canvas.width, canvas.height);
              return context.getImageData(0, 0, canvas.width, canvas.height).data;
            };
            const [a, b] = await Promise.all([pixels(left), pixels(right)]);
            // Summed-area tables make every block average, shifted or not, O(1).
            const table = (data) => {
              const width = canvas.width + 1;
              const sums = [0, 1, 2].map(() => new Float64Array(width * (canvas.height + 1)));
              for (let y = 1; y <= canvas.height; y++) {
                for (let x = 1; x <= canvas.width; x++) {
                  const offset = ((y - 1) * canvas.width + (x - 1)) * 4;
                  for (let channel = 0; channel < 3; channel++) {
                    const s = sums[channel];
                    s[y * width + x] =
                      data[offset + channel] +
                      s[(y - 1) * width + x] +
                      s[y * width + x - 1] -
                      s[(y - 1) * width + x - 1];
                  }
                }
              }
              return (x0, y0) => {
                const x1 = x0 + block;
                const y1 = y0 + block;
                return sums.map(
                  (s) =>
                    (s[y1 * width + x1] - s[y0 * width + x1] - s[y1 * width + x0] + s[y0 * width + x0]) /
                    (block * block)
                );
              };
            };
            const averageA = table(a);
            const averageB = table(b);
            const inside = (x, y) => x >= 0 && y >= 0 && x + block <= canvas.width && y + block <= canvas.height;
            const matchesNearby = (x, y) => {
              const ca = averageA(x, y);
              for (let dy = -shiftY; dy <= shiftY; dy++) {
                for (let dx = -shiftX; dx <= shiftX; dx++) {
                  if (!inside(x + dx, y + dy)) continue;
                  const cb = averageB(x + dx, y + dy);
                  if (ca.every((value, channel) => Math.abs(value - cb[channel]) <= limit)) return true;
                }
              }
              return false;
            };
            return boxes.map((box) => {
              let total = 0;
              let differing = 0;
              const x1 = Math.min(canvas.width - block, Math.floor(box.right));
              const y1 = Math.min(canvas.height - block, Math.floor(box.bottom));
              for (let y = Math.max(0, Math.floor(box.top)); y <= y1; y += block) {
                for (let x = Math.max(0, Math.floor(box.left)); x <= x1; x += block) {
                  total += 1;
                  if (!matchesNearby(x, y)) differing += 1;
                }
              }
              return { probe: box.name, differingShare: total ? differing / total : 0 };
            });
          },
          {
            left: browserShots[index],
            right: officeShots[index],
            boxes: boxesPerSlide[index],
            block: BLOCK_PX,
            limit: BLOCK_COLOUR_LIMIT,
            canvas: CANVAS,
            shiftX: SHIFT_X_PX,
            shiftY: SHIFT_Y_PX,
          }
        ))
      );
    }
    return results;
  } finally {
    await browser.close();
  }
}

function pictureBoxes(xml) {
  return Array.from(xml.matchAll(/<p:pic>[\s\S]*?<\/p:pic>/g), (match) => {
    const offset = match[0].match(/<a:off x="(-?\d+)" y="(-?\d+)"\/>/);
    const extent = match[0].match(/<a:ext cx="(\d+)" cy="(\d+)"\/>/);
    if (!offset || !extent) return null;
    return {
      left: Number(offset[1]) / EMU_PER_PT,
      top: Number(offset[2]) / EMU_PER_PT,
      right: (Number(offset[1]) + Number(extent[1])) / EMU_PER_PT,
      bottom: (Number(offset[2]) + Number(extent[2])) / EMU_PER_PT,
    };
  }).filter(Boolean);
}

function coveredShare(box, pictures) {
  const area = Math.max(1, (box.right - box.left) * (box.bottom - box.top));
  const covered = pictures.reduce((sum, picture) => {
    const width = Math.min(box.right, picture.right) - Math.max(box.left, picture.left);
    const height = Math.min(box.bottom, picture.bottom) - Math.max(box.top, picture.top);
    return sum + (width > 0 && height > 0 ? width * height : 0);
  }, 0);
  return Math.min(1, covered / area);
}

const kindsOf = (probe) => [...new Set((findingsByProbe.get(probe) ?? []).map((finding) => finding.kind))].sort();

officeDescribe('Fidelity matrix of the closed slide subset', () => {
  beforeAll(async () => {
    const executablePath = await puppeteer.executablePath();
    if (!existsSync(executablePath)) {
      throw new Error(
        `Puppeteer's browser is missing at ${executablePath}; run 'npx puppeteer browsers install chrome'.`
      );
    }
    ({ pages: browserPages, slideIds } = await measureBrowserPages(executablePath, FIXTURE, CANVAS));
    const { shots: browserShots, withImages } = await screenshotSlides(executablePath);

    outputDir = mkdtempSync(path.join(tmpdir(), 'dom-to-pptx-subset-matrix-'));
    const pptxPath = path.join(outputDir, 'subset-matrix.pptx');
    const pdfPath = path.join(outputDir, 'subset-matrix.pdf');
    const buffer = await exportHtmlToPptx(FIXTURE, {
      selector: '.slide',
      // The controlled deck path's policy: an object the converter cannot map
      // becomes a picture instead of failing the export — which this matrix
      // then reports as a `picture` defect for a probe that should stay native.
      pptxOptions: { width: 13.333333, height: 7.5, autoEmbedFonts: false, boundaryPolicy: 'rasterize' },
    });
    writeFileSync(pptxPath, buffer);
    const zip = await JSZip.loadAsync(buffer);
    const slideXml = await Promise.all(
      browserPages.map((_, index) => zip.file(`ppt/slides/slide${index + 1}.xml`).async('string'))
    );
    slideXmlAll = slideXml;
    execFileSync(
      'soffice',
      [
        `-env:UserInstallation=${pathToFileURL(path.join(outputDir, 'libreoffice-profile')).href}`,
        '--headless',
        '--convert-to',
        'pdf',
        '--outdir',
        outputDir,
        pptxPath,
      ],
      { stdio: 'pipe' }
    );
    execFileSync('pdftotext', ['-bbox', pdfPath, path.join(outputDir, 'words.html')], { stdio: 'pipe' });
    const officePages = parseOfficeWords(readFileSync(path.join(outputDir, 'words.html'), 'utf8'));
    execFileSync(
      'pdftoppm',
      [
        '-png',
        '-scale-to-x',
        String(CANVAS.width),
        '-scale-to-y',
        String(CANVAS.height),
        pdfPath,
        path.join(outputDir, 'office'),
      ],
      { stdio: 'pipe' }
    );
    const officeShots = readdirSync(outputDir)
      .filter((name) => /^office-\d+\.png$/.test(name))
      .sort((a, b) => Number(a.match(/\d+/)[0]) - Number(b.match(/\d+/)[0]))
      .map((name) => readFileSync(path.join(outputDir, name)).toString('base64'));

    findingsByProbe = new Map(PROBE_IDS.map((probe) => [probe, []]));
    metricsByProbe = new Map();
    browserPages.forEach((page, index) => {
      for (const finding of analyzePage(page, officePages[index], slideXml[index])) {
        findingsByProbe.get(finding.probe)?.push(finding);
      }
      const pictures = pictureBoxes(slideXml[index]);
      for (const probe of page.probes) {
        const share = coveredShare(probe, pictures);
        metricsByProbe.set(probe.name, { ...(metricsByProbe.get(probe.name) ?? {}), pictureShare: share });
        if (!withImages.has(probe.name) && share > PICTURE_COVER_LIMIT) {
          findingsByProbe.get(probe.name)?.push({
            probe: probe.name,
            kind: 'picture',
            detail: `${(share * 100).toFixed(0)} % of the box is a picture`,
          });
        }
      }
    });

    const toPx = (pt) => pt / PX_TO_PT;
    const boxesPerSlide = browserPages.map((page) =>
      page.probes.map((probe) => ({
        name: probe.name,
        left: toPx(probe.left),
        right: toPx(probe.right),
        top: toPx(probe.top),
        bottom: toPx(probe.bottom),
      }))
    );
    for (const { probe, differingShare } of await comparePaint(
      executablePath,
      browserShots,
      officeShots,
      boxesPerSlide
    )) {
      metricsByProbe.set(probe, { ...(metricsByProbe.get(probe) ?? {}), differingShare });
      if (differingShare > PAINT_DIFFERING_BLOCKS_LIMIT) {
        findingsByProbe
          .get(probe)
          ?.push({ probe, kind: 'paint', detail: `${(differingShare * 100).toFixed(1)} % of the box differs` });
      }
    }

    // Keeps both renderings and the deck for a look by eye; the measured shares alone
    // cannot tell a faithful probe from a comparison that looked at the wrong place.
    const artifacts = process.env.DOM_TO_PPTX_MATRIX_ARTIFACTS;
    if (artifacts) {
      browserShots.forEach((shot, index) =>
        writeFileSync(path.join(artifacts, `browser-${index + 1}.png`), Buffer.from(shot, 'base64'))
      );
      officeShots.forEach((shot, index) =>
        writeFileSync(path.join(artifacts, `office-${index + 1}.png`), Buffer.from(shot, 'base64'))
      );
      writeFileSync(path.join(artifacts, 'subset-matrix.pptx'), buffer);
    }

    if (process.env.DOM_TO_PPTX_MATRIX_REPORT) {
      const report = PROBE_IDS.map((probe) => ({
        probe,
        ...metricsByProbe.get(probe),
        kinds: kindsOf(probe),
        findings: findingsByProbe.get(probe),
      }));
      writeFileSync(process.env.DOM_TO_PPTX_MATRIX_REPORT, JSON.stringify({ slideIds, report }, null, 2));
    }
  }, 240_000);

  afterAll(() => {
    if (outputDir) rmSync(outputDir, { recursive: true, force: true });
  });

  it('measures every probe of the fixture, in the browser and in Office', () => {
    const measured = browserPages.flatMap((page) => page.probes.map((probe) => probe.name));
    expect(measured.sort()).toEqual([...PROBE_IDS].sort());
    expect(
      Object.keys(KNOWN_DEFECTS).filter((probe) => !PROBE_IDS.includes(probe)),
      'stale entries'
    ).toEqual([]);
  });

  it("keeps each picture's own alt text and no transport residue", () => {
    const descriptions = slideXmlAll.flatMap((xml) =>
      Array.from(xml.matchAll(/descr="([^"]*)"/g), (match) => match[1])
    );
    expect(descriptions.filter((text) => text.startsWith('__'))).toEqual([]);
    expect(descriptions).toEqual(expect.arrayContaining(['Testbild', 'Pfeil zwischen zwei Knoten']));
  });

  it.each(PROBE_IDS)('%s shows exactly its known defect kinds', (probe) => {
    expect(
      kindsOf(probe),
      JSON.stringify({ metrics: metricsByProbe.get(probe), findings: findingsByProbe.get(probe) }, null, 2)
    ).toEqual(KNOWN_DEFECTS[probe] ?? []);
  });
});
